export const WASH_DRY_PRICES = [
  { id: 1, description: "Shirt / T-Shirt / Blouse (Folding)", amount: 1200 },
  { id: 2, description: "Shirt / T-Shirt / Blouse (Hanging)", amount: 1300 },
  { id: 3, description: "Trouser / Skirt (Folding)", amount: 1200 },
  { id: 4, description: "Trouser / Skirt (Hanging)", amount: 1300 },
  { id: 5, description: "Gown / Coverall", amount: 2250 },
  { id: 6, description: "Blazer / Jacket", amount: 3000 },
  { id: 7, description: "Native (Up & Down)", amount: 3000 },
  { id: 8, description: "Native (3 piece Agbada)", amount: 5500 },
  { id: 9, description: "Native (Top only)", amount: 2000 },
  { id: 10, description: "Bulk Wash & Dry", amount: 6000 },
  { id: 11, description: "Big Towel", amount: 3500 },
  { id: 12, description: "Small Towel", amount: 2500 },
  { id: 13, description: "Bed Sheets & Pillow cases", amount: 3500 },
  { id: 14, description: "Duvet", amount: 5000 },
  { id: 15, description: "Towel House Robe", amount: 3000 },
  { id: 16, description: "Foot Towel", amount: 2000 },
  { id: 17, description: "Curtain (Thick)", amount: 3000 },
  { id: 18, description: "Curtain (Light)", amount: 2500 },
  { id: 19, description: "Boxers / Underwear", amount: 900 },
  { id: 20, description: "Stocking (pair)", amount: 500 },
  { id: 21, description: "Stain Removing", amount: 3500 },
];

export const IRONING_PRICES = [
  { id: 22, description: "Shirt / T-Shirt / Blouse", amount: 700 },
  { id: 23, description: "Trouser / Skirt", amount: 700 },
  { id: 24, description: "Gown / Coverall", amount: 1000 },
  { id: 25, description: "Blazer / Jacket", amount: 1500 },
  { id: 26, description: "Bed sheets & Pillow cases", amount: 900 },
  { id: 27, description: "Duvet Cover", amount: 1000 },
  { id: 28, description: "Curtain / Agbada", amount: 1500 },
  { id: 29, description: "Children School uniform", amount: 900 },
];
